image: registry.gitlab.com/quarto-forge/docker/python

pages:
  stage: deploy
  environment: production
  script:
    - quarto render project
  artifacts:
    paths:
      - public
  only:
      - main

