project:
  type: website
  output-dir: public

lang: de

execute: 
  freeze: auto

website:
  title: "HERMES"
  repo-url: https://github.com/hermes-hub/hermes-hub.github.io
  repo-actions: [edit, issue]
  repo-link-target: "_blank"
  comments: 
    hypothesis:
      openSidebar: false
  navbar:
    left:
      - text: Startseite
        file: index.qmd
      - text: Formate
        menu:
          - formate/byod-labs/index.qmd
          - formate/carpentries/index.qmd
          - formate/challenges/index.qmd
          - formate/hermes-hub/index.qmd
          - formate/kommunikationsformate/index.qmd
          - formate/oer/index.qmd
          - formate/stipendien/index.qmd
          - formate/transferwerkstatt/index.qmd
          - formate/wisskomm/index.qmd        
      - team/index.qmd        
      - text: Veranstaltungen
        menu:
          - veranstaltungen/index.qmd
          - veranstaltungen/einreichen.qmd
      - blog/index.qmd        
      - kontakt.qmd
  page-footer: 
    right: Impressum

format:
  html:
    theme: cosmo
    page-layout: full
    css: /layout/styles.css
    toc: true
