project:
  type: website
  output-dir: public
lang: de

website:
  title: "Hermeshub"
  comments: 
    hypothesis:
      openSidebar: false
  navbar:
    left:
      - text: Home
        file: index.qmd        
      - text: Personen
        file: personen/index.qmd        
      - text: Veranstaltungen
        menu:
          - veranstaltungen/index.qmd
          - veranstaltungen/einreichen.qmd
      - text: Blog
        file: blog/index.qmd        
      - text: Formate
        menu:
          - projekte/index.qmd
          - projekte/carpentries.qmd
          - projekte/challenges.qmd
          - projekte/communication.qmd
          - projekte/hub.qmd
          - projekte/labs.qmd
          - projekte/oer.qmd
          - projekte/stipendien.qmd
          - projekte/transfer.qmd
          - projekte/wisskomm.qmd
      - href: contact.qmd
        text: "Kontakt"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
